// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRoqedajHCugCAtvGEAz-vR2fuLclyiM',
    appId: '1:395975108924:web:34c8c424032d2b18e75639',
    messagingSenderId: '395975108924',
    projectId: 'education-app-16475',
    authDomain: 'education-app-16475.firebaseapp.com',
    databaseURL: 'https://education-app-16475-default-rtdb.firebaseio.com',
    storageBucket: 'education-app-16475.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_QF4Z7g6PhEBfrAM81SF0X4lBXDjFCus',
    appId: '1:395975108924:android:306d48f45aeff7d4e75639',
    messagingSenderId: '395975108924',
    projectId: 'education-app-16475',
    databaseURL: 'https://education-app-16475-default-rtdb.firebaseio.com',
    storageBucket: 'education-app-16475.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbXEPsOH0S6OsWlYEtEAt_8yDAH6-dNMw',
    appId: '1:395975108924:ios:acb55d287312209ae75639',
    messagingSenderId: '395975108924',
    projectId: 'education-app-16475',
    databaseURL: 'https://education-app-16475-default-rtdb.firebaseio.com',
    storageBucket: 'education-app-16475.appspot.com',
    iosBundleId: 'com.example.eduApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbXEPsOH0S6OsWlYEtEAt_8yDAH6-dNMw',
    appId: '1:395975108924:ios:bc9878d3329ea455e75639',
    messagingSenderId: '395975108924',
    projectId: 'education-app-16475',
    databaseURL: 'https://education-app-16475-default-rtdb.firebaseio.com',
    storageBucket: 'education-app-16475.appspot.com',
    iosBundleId: 'com.example.eduApp.RunnerTests',
  );
}
